In [1]:
import numpy as np


In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)


array([1, 2, 3])

In [5]:
type(mylist)

list

In [6]:
arr = np.array(mylist)

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr

array([1, 2, 3])

In [9]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
my_metrix=np.array(mylist)

In [12]:
my_metrix.shape

(3, 3)

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [21]:
np.ones((4)) + 2.562

array([3.562, 3.562, 3.562, 3.562])

In [25]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.random.rand(10,1)

array([[0.9216162 ],
       [0.67941175],
       [0.56012767],
       [0.86477193],
       [0.39955421],
       [0.4463422 ],
       [0.28731493],
       [0.97008502],
       [0.59946253],
       [0.5604531 ]])

In [33]:
np.random.randn(1)

array([-1.23998623])

In [34]:
#np.random.normal

In [38]:
np.random.randint(1,100,10)

array([25, 65, 58, 86,  1, 85, 55, 68, 77, 41])

In [46]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [47]:
np.random.rand(4)

array([0.58120733, 0.14267862, 0.94591918, 0.33999059])

In [48]:
arr = np.arange(25)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
ranarr = np.random.randint(0,50,10)

In [53]:
ranarr

array([10, 21, 27, 28, 48,  4,  1, 42, 41, 20])

In [57]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
ranarr.max()

48

In [61]:
ranarr.min()

1

In [62]:
ranarr


array([10, 21, 27, 28, 48,  4,  1, 42, 41, 20])

In [63]:
ranarr.argmax()

4

In [64]:
ranarr.argmin()

6

In [65]:
ranarr.dtype

dtype('int32')

In [66]:
arr = np.arange(0,11)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr[8]

8

In [69]:
arr[1:5]

array([1, 2, 3, 4])

In [70]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [71]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr +100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [74]:
arr ^ 2

array([ 2,  3,  0,  1,  6,  7,  4,  5, 10, 11,  8], dtype=int32)

In [75]:
slice_of_arr = arr[0:6]

In [76]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [77]:
slice_of_arr[:]=99

In [78]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [79]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [80]:
# INDEXING on 2d array 

In [82]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [83]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [84]:
arr_2d.shape

(3, 3)

In [87]:
arr_2d[1,1]

25

In [88]:
arr_2d[2,2]

45

In [89]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [92]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [93]:
arr= np.arange(1,11)

In [94]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [96]:
bool_arr = arr > 4

In [97]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [98]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [99]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [100]:
arr[arr <= 6]

array([1, 2, 3, 4, 5, 6])

In [101]:
arr = np.arange(0,10)

In [102]:
arr +100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [103]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [105]:
arr ^2

array([ 2,  3,  0,  1,  6,  7,  4,  5, 10, 11], dtype=int32)

In [106]:
1/arr

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_4688\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [107]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [108]:
np.log(arr)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_4688\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [109]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [110]:
arr.sum()

45

In [111]:
arr.mean()

4.5

In [112]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [113]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [115]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [116]:
arr_2d.sum(axis=1)

array([10, 26, 42])

In [117]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [126]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [127]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [128]:
np.random.rand(1)

array([0.54446869])

In [129]:
np.random.randn(25)

array([-0.04002214, -0.57682082, -0.06093606,  0.99777819,  1.77504465,
       -1.33787438,  0.79831093, -1.76290856, -0.26470411, -0.05702478,
       -1.93448324, -1.49527076,  0.04546801,  2.32689445,  0.47101579,
       -0.95354059, -0.17148383, -0.18949414, -0.08206915, -0.05543088,
        1.33522561, -0.26534612,  1.57862401,  1.11172409, -0.02313095])

In [137]:
np.arange(0,1,0.01).reshape(10,10)

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])