In [1]:
import torch

In [2]:
import numpy as np


In [3]:
torch.__version__

'2.3.0'

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
print(arr)

[1 2 3 4 5]


In [8]:
x=torch.from_numpy(arr)

In [9]:
type(x)

torch.Tensor

In [10]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [11]:
x.dtype

torch.int32

In [15]:
arr2d = np.arange(0.0,12.0).reshape(4,3)

In [18]:
x2=torch.from_numpy(arr2d)

In [19]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [20]:
my_arr = np.arange(0,10)

In [21]:
my_tensor = torch.tensor(my_arr)

In [22]:
my_other_tensor = torch.from_numpy(my_arr)

In [23]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [24]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [25]:
my_arr[0]=99

In [26]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [27]:
my_other_tensor

tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9], dtype=torch.int32)

In [28]:
new_arr = np.array([1,2,3])

In [29]:
new_arr.dtype

dtype('int32')

In [30]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [32]:
my_tensor=torch.Tensor(new_arr)

In [34]:
my_tensor.dtype

torch.float32

In [35]:
torch.empty(2,2)

tensor([[9.2196e-41, 2.3750e+00],
        [0.0000e+00, 0.0000e+00]])

In [37]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [38]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [47]:
torch.arange(1,12,2).reshape(3,2)

tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])

In [48]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [49]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [50]:
my_tensor = torch.tensor([1,2,3])

In [51]:
my_tensor.dtype

torch.int64

In [56]:
my_tensor=my_tensor.type(torch.int32)

In [57]:
my_tensor.dtype

torch.int32

In [58]:
torch.rand(4,3)

tensor([[0.4647, 0.0757, 0.0637],
        [0.5486, 0.9085, 0.8171],
        [0.9869, 0.8560, 0.8397],
        [0.5527, 0.0906, 0.0308]])

In [59]:
torch.randn(4,3)

tensor([[-0.6544,  1.8572, -1.0142],
        [ 1.4318,  1.1104,  0.0403],
        [ 0.0149, -0.9017, -1.1325],
        [-1.1725, -1.7606,  0.1810]])

In [60]:
torch.randint(low=0,high=10,size=(5,5))

tensor([[1, 2, 0, 7, 1],
        [8, 0, 4, 5, 4],
        [0, 6, 1, 9, 1],
        [7, 4, 9, 2, 3],
        [3, 3, 9, 2, 0]])

In [61]:
x = torch.zeros(2,5)

In [62]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [64]:
torch.rand_like(x)

tensor([[0.6216, 0.8273, 0.3031, 0.7610, 0.2059],
        [0.8142, 0.4387, 0.9269, 0.3198, 0.6164]])

In [65]:
torch.randint_like(x,low=0,high=11)

tensor([[ 0.,  0.,  0.,  0.,  3.],
        [10., 10.,  5.,  7.,  6.]])

In [66]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [67]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [69]:
x=torch.arange(6).reshape(3,2)

In [70]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [71]:
x[1,1]

tensor(3)

In [72]:
x[:,1]

tensor([1, 3, 5])

In [73]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [74]:
x = torch.arange(10)

In [75]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [77]:
x = x.reshape(2,5)

In [78]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [79]:
x = torch.arange(10)

In [80]:
x.shape

torch.Size([10])

In [81]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [82]:
z = x.view(2,5)

In [83]:
x[0]= 999

In [84]:
x

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [85]:
z

tensor([[999,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [86]:
x = torch.arange(10)

In [87]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
x.shape

torch.Size([10])

In [92]:
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [93]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [94]:
a = torch.arange(4)

In [95]:
a

tensor([0, 1, 2, 3])

In [96]:
b = torch.arange(4,8)

In [97]:
b

tensor([4, 5, 6, 7])

In [98]:
torch.add(a,b)

tensor([ 4,  6,  8, 10])

In [99]:
a.mul_(b)

tensor([ 0,  5, 12, 21])

In [100]:
a

tensor([ 0,  5, 12, 21])

In [101]:
 a = torch.arange(4)

In [102]:
a

tensor([0, 1, 2, 3])

In [103]:
b

tensor([4, 5, 6, 7])

In [104]:
a.mul(b)

tensor([ 0,  5, 12, 21])

In [105]:
a

tensor([0, 1, 2, 3])

In [106]:
a.dot(b)

tensor(38)

In [107]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [108]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [109]:
b= torch.tensor([[6,7],[8,9],[10,11]])

In [110]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [111]:
a.shape

torch.Size([2, 3])

In [112]:
b.shape

torch.Size([3, 2])

In [113]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [114]:
x = torch.tensor([2.,3.,4.,5.])

In [115]:
x

tensor([2., 3., 4., 5.])

In [116]:
x.norm()

tensor(7.3485)

In [117]:
x.numel()

4

In [118]:
len(x)

4

In [119]:
len(a)

2

In [120]:
a.numel()

6